DECLARE
	--BASE ALFABÉTICA -> A(65)-Z(90) -> 26 ELEMENTOS
	FUNCTION ALPHAL(P_DECIMAL_NUMBER INTEGER)
	RETURN	VARCHAR2
	IS
		V_AUX		INTEGER;
		V_ANSWER	VARCHAR2(32) := '';
		V_BASE		INTEGER := ASCII('Z')-ASCII('A')+1;--DOMÍNIO DA BASE ALFABÉTICA
	BEGIN
		V_AUX := P_DECIMAL_NUMBER;
		
		WHILE V_AUX >= V_BASE
		LOOP
			V_ANSWER := CHR(MOD(V_AUX,V_BASE)+ASCII('A'))||V_ANSWER;
			V_AUX := FLOOR(V_AUX/V_BASE);
		END LOOP;
			V_ANSWER := CHR(V_AUX+ASCII('A'))||V_ANSWER;
		RETURN V_ANSWER;
	END;
BEGIN
	FOR I IN 0..30
	LOOP 
	DBMS_OUTPUT.PUT_LINE(ALPHAL(I));
	END LOOP;
END;
