/*ADDRESS=LOCALHOST PORT=1521 SERVICE=ORCL USER=DEV PASSWORD=DEV
	SCRIPT QUE COMPILA TODOS OS OBJETOS DO BANCO.
	
	DBMS_UTILITY.EXEC_DDL_STATEMENT FOI INUTILIZADO. POIS GERAVA COMANDOS COM A CLAUSULA NOWAIT, CAUSANDO A EXCESSAO:
	[1]: (Error): ORA-00054: resource busy and acquire with NOWAIT specified ORA-06512: at "SYS.DBMS_UTILITY", line 478 ORA-06512: at line 26
	DURANTE A EXECUÇÃO DO MESMO SE HOUVEREM PROCESSOS PENDENTES NA BASE.
*/
DECLARE
	EXTCOUNT INTEGER;
	INTERNCOUNT INTEGER;
BEGIN
	
	EXTCOUNT := 0;
	INTERNCOUNT := -1;
	WHILE EXTCOUNT != INTERNCOUNT
	LOOP
		EXTCOUNT := INTERNCOUNT;
		
	    FOR I IN (
	        SELECT 'ALTER ' || DECODE(OBJECT_TYPE,'PACKAGE BODY','PACKAGE',OBJECT_TYPE) || ' ' || OBJECT_NAME || DECODE(OBJECT_TYPE,'PACKAGE BODY',' COMPILE BODY',' COMPILE') STMT
	        FROM USER_OBJECTS 
	        WHERE STATUS = 'INVALID'
	    )LOOP
	        BEGIN
		    dbms_output.put_line(I.STMT);
	            --DBMS_UTILITY.EXEC_DDL_STATEMENT(I.STMT);
	            EXECUTE IMMEDIATE I.STMT;
	        EXCEPTION WHEN OTHERS THEN
	        	NULL;
	        END;
	    END LOOP;
	    
	    BEGIN
	    	dbms_output.put_line('PURGE RECYCLEBIN');
	    	--DBMS_UTILITY.EXEC_DDL_STATEMENT ('PURGE RECYCLEBIN');
	    	EXECUTE IMMEDIATE 'PURGE RECYCLEBIN';
	    EXCEPTION WHEN OTHERS THEN
	       NULL;
	    END;
	    SELECT COUNT(*) INTO INTERNCOUNT FROM USER_OBJECTS WHERE STATUS = 'INVALID';
	END LOOP;
END;
/
	SELECT OBJECT_NAME,OBJECT_TYPE,STATUS FROM USER_OBJECTS WHERE STATUS = 'INVALID'

