--SELECT * FROM USER_OBJECTS

DECLARE
    STMT VARCHAR2(4000);
    DESTINY_DATABASE_NAME VARCHAR2(64) := '&DESTINY_DATABASE_NAME';
    DESTINY_DATABASE_LINK_NAME VARCHAR2(64) := '&DESTINY_DATABASE_LINK_NAME';
BEGIN

    FOR I IN(SELECT TABLE_NAME FROM DICT WHERE TABLE_NAME LIKE 'USER%') LOOP
--        STMT := 'CREATE OR REPLACE VIEW '||I.TABLE_NAME||'_'||' AS SELECT * FROM '||I.TABLE_NAME||'@'||DESTINY_DATABASE_LINK_NAME;
        STMT := 'CREATE OR REPLACE SYNONYM '||I.TABLE_NAME||'_ FOR '||I.TABLE_NAME||'@'||DESTINY_DATABASE_LINK_NAME;
        
        BEGIN
            EXECUTE IMMEDIATE STMT;
            --DBMS_OUTPUT.PUT_LINE(I.TABLE_NAME||'_'||DESTINY_DATABASE_NAME||': OK');
        EXCEPTION WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE(I.TABLE_NAME||'_'||DESTINY_DATABASE_NAME||': '||SQLERRM);
        END;
    END LOOP;
    
    FOR I IN(SELECT OBJECT_NAME FROM USER_OBJECTS@&&DESTINY_DATABASE_LINK_NAME 
            WHERE OBJECT_TYPE IN ('SYNONYM','FUNCTION','SEQUENCE','PACKAGE','PROCEDURE','VIEW','TABLE')
    ) LOOP
        STMT := 'CREATE OR REPLACE SYNONYM '||I.OBJECT_NAME||' FOR '||I.OBJECT_NAME||'@'||DESTINY_DATABASE_LINK_NAME;
        
        BEGIN
            EXECUTE IMMEDIATE STMT;
            --DBMS_OUTPUT.PUT_LINE(I.OBJECT_NAME||'_'||DESTINY_DATABASE_NAME||': OK');
        EXCEPTION WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE(I.OBJECT_NAME||'_'||DESTINY_DATABASE_NAME||': '||SQLERRM);
        END;
    END LOOP;
END;





