SET SERVEROUTPUT ON SIZE 400000
SET FEEDBACK OFF

DECLARE
   CURSOR C_CTX IS SELECT 
	 SYS_CONTEXT('USERENV','ACTION') ACTION,
	 SYS_CONTEXT('USERENV','AUDITED_CURSORID') AUDITED_CURSORID,
	 SYS_CONTEXT('USERENV','AUTHENTICATED_IDENTITY') AUTHENTICATED_IDENTITY,
	 SYS_CONTEXT('USERENV','AUTHENTICATION_DATA') AUTHENTICATION_DATA,
	 SYS_CONTEXT('USERENV','AUTHENTICATION_METHOD') AUTHENTICATION_METHOD,
	 SYS_CONTEXT('USERENV','AUTHENTICATION_TYPE') AUTHENTICATION_TYPE,
	 SYS_CONTEXT('USERENV','BG_JOB_ID') BG_JOB_ID,
	 SYS_CONTEXT('USERENV','CLIENT_IDENTIFIER') CLIENT_IDENTIFIER,
	 SYS_CONTEXT('USERENV','CLIENT_INFO') CLIENT_INFO,
	 SYS_CONTEXT('USERENV','CURRENT_BIND') CURRENT_BIND,
	 SYS_CONTEXT('USERENV','CURRENT_SCHEMA') CURRENT_SCHEMA,
	 SYS_CONTEXT('USERENV','CURRENT_SCHEMAID') CURRENT_SCHEMAID,
	 SYS_CONTEXT('USERENV','CURRENT_SQL') CURRENT_SQL,
	 SYS_CONTEXT('USERENV','CURRENT_SQL1') CURRENT_SQL1,
	 SYS_CONTEXT('USERENV','CURRENT_SQL2') CURRENT_SQL2,
	 SYS_CONTEXT('USERENV','CURRENT_SQL_LENGTH') CURRENT_SQL_LENGTH,
	 SYS_CONTEXT('USERENV','CURRENT_USER') CURRENT_USER,
	 SYS_CONTEXT('USERENV','CURRENT_USERID') CURRENT_USERID,
	 SYS_CONTEXT('USERENV','DB_DOMAIN') DB_DOMAIN,
	 SYS_CONTEXT('USERENV','DB_NAME') DB_NAME,
	 SYS_CONTEXT('USERENV','DB_UNIQUE_NAME') DB_UNIQUE_NAME,
	 SYS_CONTEXT('USERENV','ENTERPRISE_IDENTITY') ENTERPRISE_IDENTITY,
	 SYS_CONTEXT('USERENV','ENTRYID') ENTRYID,
	 SYS_CONTEXT('USERENV','EXTERNAL_NAME') EXTERNAL_NAME,
	 SYS_CONTEXT('USERENV','FG_JOB_ID') FG_JOB_ID,
	 SYS_CONTEXT('USERENV','GLOBAL_CONTEXT_MEMORY') GLOBAL_CONTEXT_MEMORY,
	 SYS_CONTEXT('USERENV','GLOBAL_UID') GLOBAL_UID,
	 SYS_CONTEXT('USERENV','HOST') HOST,
	 SYS_CONTEXT('USERENV','IDENTIFICATION_TYPE') IDENTIFICATION_TYPE,
	 SYS_CONTEXT('USERENV','INSTANCE') INSTANCE,
	 SYS_CONTEXT('USERENV','INSTANCE_NAME') INSTANCE_NAME,
	 SYS_CONTEXT('USERENV','IP_ADDRESS') IP_ADDRESS,
	 SYS_CONTEXT('USERENV','ISDBA') ISDBA,
	 SYS_CONTEXT('USERENV','LANG') LANG,
	 SYS_CONTEXT('USERENV','LANGUAGE') LANGUAGE,
	 SYS_CONTEXT('USERENV','MODULE') MODULE,
	 SYS_CONTEXT('USERENV','NETWORK_PROTOCOL') NETWORK_PROTOCOL,
	 SYS_CONTEXT('USERENV','NLS_CALENDAR') NLS_CALENDAR,
	 SYS_CONTEXT('USERENV','NLS_CURRENCY') NLS_CURRENCY,
	 SYS_CONTEXT('USERENV','NLS_DATE_FORMAT') NLS_DATE_FORMAT,
	 SYS_CONTEXT('USERENV','NLS_DATE_LANGUAGE') NLS_DATE_LANGUAGE,
	 SYS_CONTEXT('USERENV','NLS_SORT') NLS_SORT,
	 SYS_CONTEXT('USERENV','NLS_TERRITORY') NLS_TERRITORY,
	 SYS_CONTEXT('USERENV','OS_USER') OS_USER,
	 SYS_CONTEXT('USERENV','POLICY_INVOKER') POLICY_INVOKER,
	 SYS_CONTEXT('USERENV','PROXY_ENTERPRISE_IDENTITY') PROXY_ENTERPRISE_IDENTITY,
	 SYS_CONTEXT('USERENV','PROXY_USER') PROXY_USER,
	 SYS_CONTEXT('USERENV','PROXY_USERID') PROXY_USERID,
	 SYS_CONTEXT('USERENV','SERVER_HOST') SERVER_HOST,
	 SYS_CONTEXT('USERENV','SERVICE_NAME') SERVICE_NAME,
	 SYS_CONTEXT('USERENV','SESSION_USER') SESSION_USER,
	 SYS_CONTEXT('USERENV','SESSION_USERID') SESSION_USERID,
	 SYS_CONTEXT('USERENV','SESSIONID') SESSIONID,
	 SYS_CONTEXT('USERENV','SID') SID,
	 SYS_CONTEXT('USERENV','STATEMENTID') STATEMENTID,
	 SYS_CONTEXT('USERENV','TERMINAL') TERMINAL
   FROM DUAL;

   CTX C_CTX%ROWTYPE;

   FUNCTION PAD (S VARCHAR2, PADSIZE NUMBER := 25, PADCHAR VARCHAR2 := ' ') 
   RETURN VARCHAR2 IS
   BEGIN
     RETURN RPAD(S,PADSIZE,PADCHAR);
   END PAD;

   PROCEDURE PRINT(S VARCHAR2) IS
   BEGIN
      DBMS_OUTPUT.PUT_LINE(S);
   END PRINT;

   PROCEDURE NEWLN IS
   BEGIN
      PRINT(CHR(13)||CHR(10));
   END NEWLN;

BEGIN

   OPEN C_CTX;
   FETCH C_CTX INTO CTX;
   CLOSE C_CTX;

   NEWLN;
   PRINT('CONTEXTO DA CONEXAO');
   PRINT('===================');
   NEWLN;

   PRINT('Detalhes do Usuario');
   PRINT('-------------------');
   PRINT(PAD('SESSION ID: ')||CTX.SESSIONID);
   PRINT(PAD('SESSION USER ID: ')||CTX.SESSION_USERID||'/'||CTX.SESSION_USER);
   PRINT(PAD('CURRENT USER ID: ')||CTX.CURRENT_USERID||'/'||CTX.CURRENT_USER);
   PRINT(PAD('IS DBA: ')||CTX.ISDBA);
   NEWLN;


   PRINT('Detalhes da maquina/rede');
   PRINT('------------------------');
   PRINT(PAD('TERMINAL: ')||CTX.TERMINAL);
   PRINT(PAD('HOST: ')||CTX.HOST);
   PRINT(PAD('OS USER: ')||CTX.OS_USER);
   PRINT(PAD('IP ADDRESS: ')||CTX.IP_ADDRESS);
   PRINT(PAD('NETWORK PROTOCOL: ')||CTX.NETWORK_PROTOCOL);
   PRINT(PAD('AUTHENTICATION TYPE: ')||CTX.AUTHENTICATION_TYPE);
   NEWLN;

   PRINT('Configuracoes NLS');
   PRINT('-----------------');
   PRINT(PAD('NLS TERRITORY: ')||CTX.NLS_TERRITORY);
   PRINT(PAD('NLS CURRENCY: ')||CTX.NLS_CURRENCY);
   PRINT(PAD('NLS DATE FORMAT: ')||CTX.NLS_DATE_FORMAT);
   PRINT(PAD('NLS DATE LANGUAGE: ')||CTX.NLS_DATE_LANGUAGE);
   PRINT(PAD('NLS SORT: ')||CTX.NLS_SORT);
   NEWLN;

   PRINT('Banco de dados');
   PRINT('--------------');
   PRINT(PAD('DB NAME: ')||CTX.DB_NAME);
   PRINT(PAD('DB DOMAIN: ')||CTX.DB_DOMAIN);
   PRINT(PAD('LANGUAGE: ')||CTX.LANGUAGE);
   NEWLN;

END;
/

SET FEEDBACK ON

