CREATE OR REPLACE PROCEDURE PROC_ASSASSIN AS

-----------------------------------------
-- Selecionando as vítimas --------------
-----------------------------------------

CURSOR C_VICTIM IS
SELECT 'ALTER SYSTEM KILL SESSION ''' || A.SID || ',' || A.SERIAL# || ''''
FROM V$SESSION A
WHERE A.STATUS = 'INACTIVE' AND A.USERNAME IN (SELECT USER FROM DUAL);

A_VICTIM VARCHAR2(100) :='';

BEGIN

IF C_VICTIM%ISOPEN THEN
CLOSE C_VICTIM;
END IF;

OPEN C_VICTIM;

LOOP
FETCH C_VICTIM INTO A_VICTIM;
EXIT WHEN C_VICTIM%NOTFOUND;
EXECUTE IMMEDIATE A_VICTIM;
END LOOP;

END PROC_ASSASSIN;
