/*

Select que retorna todas as colunas da BASE_PRINCIPAL que não existem na BASE_COMPARATIVA
Caso não haja DB_LINK, utilizar valores nulos. Se houver DB_LINK, utilizar o nome do DBLINK precedido de @...


-----------  UTILIZAÇÃO SEM DB_LINK -------------------------

PARA FUNCIONAR, DEVE-SE TER A GRANT "SELECT ANY TABLE"

PARA TESTAR SE POSSUI A GRANT, BASTA VERIFICAR SE O SELECT ABAIXO RETORNA OS USUÁRIOS DAS BASES
SELECT DISTINCT OWNER FROM ALL_TABLES;

*/


-- APENAS COLUNAS DE TABELAS JÁ EXISTENTES -------------------------------------
SELECT DISTINCT
BASE_PRINCIPAL.TABLE_NAME,BASE_PRINCIPAL.COLUMN_NAME,BASE_PRINCIPAL.DATA_TYPE,BASE_PRINCIPAL.DATA_LENGTH,BASE_PRINCIPAL.DATA_PRECISION,BASE_PRINCIPAL.DATA_SCALE,BASE_PRINCIPAL.NULLABLE--,SUBSTR(BASE_PRINCIPAL.DATA_DEFAULT,1,1000) DATA_DEFAULT
--,BASE_COMPARATIVA.TABLE_NAME,BASE_COMPARATIVA.COLUMN_NAME,BASE_COMPARATIVA.DATA_TYPE,BASE_COMPARATIVA.DATA_LENGTH,BASE_COMPARATIVA.DATA_PRECISION,BASE_COMPARATIVA.DATA_SCALE,BASE_COMPARATIVA.NULLABLE,SUBSTR(BASE_COMPARATIVA.DATA_DEFAULT,1,1000) DATA_DEFAULT
FROM ALL_TAB_COLUMNS&DB_LINK_BASE_PRINCIPAL                     BASE_PRINCIPAL
INNER JOIN ALL_TABLES&&DB_LINK_BASE_PRINCIPAL                    TABELA_PRINCIPAL
ON  TABELA_PRINCIPAL.OWNER                       = UPPER('&BASE_PRINCIPAL')
    AND BASE_PRINCIPAL.TABLE_NAME = TABELA_PRINCIPAL.TABLE_NAME
INNER JOIN ALL_TABLES&DB_LINK_BASE_COMPARATIVA                  TABELA_COMPARATIVA
ON TABELA_PRINCIPAL.TABLE_NAME = TABELA_COMPARATIVA.TABLE_NAME
    AND TABELA_COMPARATIVA.OWNER                = UPPER('&BASE_COMPARATIVA')
LEFT JOIN ALL_TAB_COLUMNS&&DB_LINK_BASE_COMPARATIVA              BASE_COMPARATIVA
ON BASE_COMPARATIVA.OWNER                       = UPPER('&&BASE_COMPARATIVA')
    AND NVL(BASE_PRINCIPAL.TABLE_NAME,'NULL')   = NVL(BASE_COMPARATIVA.TABLE_NAME,'NULL') 
    AND NVL(BASE_PRINCIPAL.COLUMN_NAME,'NULL')  = NVL(BASE_COMPARATIVA.COLUMN_NAME,'NULL') 
    AND NVL(BASE_PRINCIPAL.DATA_TYPE,'NULL')    = NVL(BASE_COMPARATIVA.DATA_TYPE,'NULL')
    AND NVL(BASE_PRINCIPAL.DATA_LENGTH,0)       = NVL(BASE_COMPARATIVA.DATA_LENGTH,0)
    AND NVL(BASE_PRINCIPAL.DATA_PRECISION,0)    = NVL(BASE_COMPARATIVA.DATA_PRECISION,0)
    AND NVL(BASE_PRINCIPAL.DATA_SCALE,0)        = NVL(BASE_COMPARATIVA.DATA_SCALE,0)
    AND NVL(BASE_PRINCIPAL.NULLABLE,'NULL')     = NVL(BASE_COMPARATIVA.NULLABLE,'NULL')
--    AND NVL(BASE_PRINCIPAL.DATA_DEFAULT,'NULL')     = NVL(BASE_COMPARATIVA.DATA_DEFAULT,'NULL')
WHERE BASE_PRINCIPAL.OWNER                      = UPPER('&&BASE_PRINCIPAL')
    AND BASE_COMPARATIVA.COLUMN_NAME IS NULL
    --AND (BASE_PRINCIPAL.TABLE_NAME = 'CIAP_RGR_SALDO' OR BASE_COMPARATIVA.TABLE_NAME = 'CIAP_RGR_SALDO')
ORDER BY 1,2



-- APENAS COLUNAS COM DEFAULT E NOT NULL DE TABELAS JÁ EXISTENTES -------------------------------------
SELECT DISTINCT
BASE_PRINCIPAL.TABLE_NAME,BASE_PRINCIPAL.COLUMN_NAME,BASE_PRINCIPAL.DATA_TYPE,BASE_PRINCIPAL.DATA_LENGTH,BASE_PRINCIPAL.DATA_PRECISION,BASE_PRINCIPAL.DATA_SCALE,BASE_PRINCIPAL.NULLABLE--,SUBSTR(BASE_PRINCIPAL.DATA_DEFAULT,1,1000) DATA_DEFAULT
FROM ALL_TAB_COLUMNS&DB_LINK_BASE_PRINCIPAL                     BASE_PRINCIPAL
INNER JOIN ALL_TABLES&&DB_LINK_BASE_PRINCIPAL                    TABELA_PRINCIPAL
ON  TABELA_PRINCIPAL.OWNER                       = UPPER('&BASE_PRINCIPAL')
    AND BASE_PRINCIPAL.TABLE_NAME = TABELA_PRINCIPAL.TABLE_NAME
INNER JOIN ALL_TABLES&DB_LINK_BASE_COMPARATIVA                  TABELA_COMPARATIVA
ON TABELA_PRINCIPAL.TABLE_NAME = TABELA_COMPARATIVA.TABLE_NAME
    AND TABELA_COMPARATIVA.OWNER                = UPPER('&BASE_COMPARATIVA')
LEFT JOIN ALL_TAB_COLUMNS&&DB_LINK_BASE_COMPARATIVA              BASE_COMPARATIVA
ON BASE_COMPARATIVA.OWNER                       = UPPER('&&BASE_COMPARATIVA')
    AND NVL(BASE_PRINCIPAL.TABLE_NAME,'NULL')   = NVL(BASE_COMPARATIVA.TABLE_NAME,'NULL') 
    AND NVL(BASE_PRINCIPAL.COLUMN_NAME,'NULL')  = NVL(BASE_COMPARATIVA.COLUMN_NAME,'NULL') 
    AND NVL(BASE_PRINCIPAL.DATA_TYPE,'NULL')    = NVL(BASE_COMPARATIVA.DATA_TYPE,'NULL')
    AND NVL(BASE_PRINCIPAL.DATA_LENGTH,0)       = NVL(BASE_COMPARATIVA.DATA_LENGTH,0)
    AND NVL(BASE_PRINCIPAL.DATA_PRECISION,0)    = NVL(BASE_COMPARATIVA.DATA_PRECISION,0)
    AND NVL(BASE_PRINCIPAL.DATA_SCALE,0)        = NVL(BASE_COMPARATIVA.DATA_SCALE,0)
    AND NVL(BASE_PRINCIPAL.NULLABLE,'NULL')     = NVL(BASE_COMPARATIVA.NULLABLE,'NULL')
--    AND NVL(BASE_PRINCIPAL.DATA_DEFAULT,'NULL')     = NVL(BASE_COMPARATIVA.DATA_DEFAULT,'NULL')
WHERE BASE_PRINCIPAL.OWNER                      = UPPER('&&BASE_PRINCIPAL')
    AND BASE_PRINCIPAL.DATA_DEFAULT IS NOT NULL 
    and BASE_PRINCIPAL.NULLABLE = 'Y'
    AND BASE_COMPARATIVA.COLUMN_NAME IS NULL
    --AND (BASE_PRINCIPAL.TABLE_NAME = 'CIAP_RGR_SALDO' OR BASE_COMPARATIVA.TABLE_NAME = 'CIAP_RGR_SALDO')
ORDER BY 1,2




-- apenas para verificação e comparação....
SELECT * FROM all_tab_columns 
WHERE owner = 'RCP_SP8' AND TABLE_NAME = 'TABELA1' AND COLUMN_NAME = 'COLUMN1';
SELECT * FROM all_tab_columns 
WHERE owner = 'RCP_SP9' AND TABLE_NAME = 'TABELA1' AND COLUMN_NAME = 'COLUMN1';


--verifica se a tabela existe....
SELECT * FROM all_tab_columns 
WHERE owner = 'RCP_SP8' AND TABLE_NAME = 'TABELA1';
SELECT * FROM all_tab_columns 
WHERE owner = 'RCP_SP9' AND TABLE_NAME = 'TABELA1';








