/*
Recupera sql da sessão do user
*/
SELECT 
       SQL_TEXT         SQL
       ,OPTIMIZER_MODE  MODO
       ,OPTIMIZER_COST  CUSTO
       ,USERNAME        USUARIO
FROM V$SQL, DBA_USERS
WHERE PARSING_SCHEMA_ID = USER_ID
      AND username = '&NOME_DO_USUARIO' --COLOQUE O NOME DO USUÁRIO AQUI
      AND TO_DATE(FIRST_LOAD_TIME,'YYYY-MM-DD/HH24:MI:SS') >= TRUNC(SYSDATE)
ORDER BY TO_DATE(FIRST_LOAD_TIME,'YYYY-MM-DD/HH24:MI:SS') DESC 
